- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Import user role
      import_role:
        name: user-role
    - name: Import apps role
      import_role:
        name: apps-role
