- name: Update apt cache
  apt:
    update_cache: yes
- name: Installing vim, nano, curl
  apt:
    name: ['vim', 'nano', 'curl']
    state: latest
- name: Installing thin-provisioning-tools, lvm2
  apt:
    name: ['thin-provisioning-tools', 'lvm2']
    state: latest
- name: Installing apt-transport-https, ca-certificates, gnupg-agent, software-properties-common
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'gnupg-agent', 'software-properties-common']
    state: latest
- name: Installing stable docker-ce, docker-ce-cli, containerd.io
  apt:
    name: docker.io
    state: present
- name: Installing kubectl, kubeadm, kubelet
  apt:
    name: ['kubectl', 'kubeadm', 'kubelet']
    state: latest
