- name: Disable SWAP in fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent
- name: Disable SWAP in the system
  command:
    cmd: swapoff -a
- name: Downloading minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/v1.6.2/minikube-linux-amd64
    dest: /vagrant/minikube
    owner: root
    group: root
    mode: +x
- name: Check ca-certificates directory exists
  stat:
    path: /usr/share/ca-certificates
  register: stat_result
- name: Creating directory for certificates if not exists
  file:
    path: /usr/share/ca-certificates
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: stat_result.stat.exists == False
- import_tasks: add-repos.yml
- import_tasks: install-packages.yml
- import_tasks: enable-services.yml
